// utils/categoryContent.js

const categoryContent = {
    "Rent Agreements": [
      { name: "House rent agreement", path: "/rent-agreements/house-rent-agreement" },
      { name: "Flat rent agreement", path: "/rent-agreements/flat-rent-agreement" },
      { name: "Furnished house rent agreement", path: "/rent-agreements/furnished-house-rent-agreement" },
      { name: "Quick rental agreement", path: "/rent-agreements/quick-rental-agreement" },
      { name: "Residential lease agreement", path: "/rent-agreements/residential-lease-agreement" },
      { name: "Furnished flat rental agreement", path: "/rent-agreements/furnished-flat-rental-agreement" },
      { name: "Room rental agreement", path: "/rent-agreements/room-rental-agreement" },
      { name: "Lease of furnished house for residential purpose", path: "/rent-agreements/lease-furnished-house-residential" },
      { name: "Paying guest agreement", path: "/rent-agreements/paying-guest-agreement" },
    ],
    "Business Agreements": [
      { name: "Partnership Deed", path: "/business-agreements/partnership-deed" },
      { name: "Office Sharing Agreement", path: "/business-agreements/office-sharing-agreement" },
      { name: "NOC form Landlord", path: "/business-agreements/noc-form-landlord" },
      { name: "Memorandum of understanding (property)", path: "/business-agreements/memorandum-understanding-property" },
      { name: "Confidentiality agreement", path: "/business-agreements/confidentiality-agreement" },
      { name: "Recognition letter", path: "/business-agreements/recognition-letter" },
      { name: "Code of conduct", path: "/business-agreements/code-of-conduct" },
      { name: "Exit policy", path: "/business-agreements/exit-policy" },
      { name: "Procurement Agreement", path: "/business-agreements/procurement-agreement" },
      { name: "Exclusive agreement", path: "/business-agreements/exclusive-agreement" },
      { name: "Trust deed", path: "/business-agreements/trust-deed" },
      { name: "The Limited Liability Partnership agreement", path: "/business-agreements/llp-agreement" },
      { name: "Agency Agreement", path: "/business-agreements/agency-agreement" },
      { name: "Hire Purchase Agreement", path: "/business-agreements/hire-purchase-agreement" },
      { name: "Deed of dissolution", path: "/business-agreements/deed-of-dissolution" },
      { name: "Deed of Retirement", path: "/business-agreements/deed-of-retirement" },
    ],
    "Employment Agreements": [
      { name: "Offer letter", path: "/employment-agreements/offer-letter" },
      { name: "Appointment letter", path: "/employment-agreements/appointment-letter" },
      { name: "Confirmation letter", path: "/employment-agreements/confirmation-letter" },
      { name: "Fixed term employment agreement", path: "/employment-agreements/fixed-term-employment" },
      { name: "Ad hoc employment agreement", path: "/employment-agreements/ad-hoc-employment" },
      { name: "Resignation letter", path: "/employment-agreements/resignation-letter" },
      { name: "Letter of termination", path: "/employment-agreements/letter-of-termination" },
      { name: "Consultancy agreement", path: "/employment-agreements/consultancy-agreement" },
      { name: "Advisors agreement", path: "/employment-agreements/advisors-agreement" },
      { name: "Retainer ship agreement", path: "/employment-agreements/retainer-ship-agreement" },
      { name: "Employment agreement", path: "/employment-agreements/employment-agreement" },
      { name: "Compensation agreement", path: "/employment-agreements/compensation-agreement" },
      { name: "Collective bargaining agreement", path: "/employment-agreements/collective-bargaining-agreement" },
      { name: "Wage agreement", path: "/employment-agreements/wage-agreement" },
      { name: "Agreement to refer disputes to arbitration", path: "/employment-agreements/arbitration-agreement" },
      { name: "Contractor agreement", path: "/employment-agreements/contractor-agreement" },
      { name: "On the job training agreement", path: "/employment-agreements/job-training-agreement" },
      { name: "Non-compete agreement", path: "/employment-agreements/non-compete-agreement" },
      { name: "Agreement for logistics services", path: "/employment-agreements/logistics-services-agreement" },
    ],
    "Affidavits": [
      { name: "Address Proof Affidavit", path: "/affidavits/address-proof-affidavit" },
      { name: "Affidavit For Change Of Name", path: "/affidavits/change-of-name" },
      { name: "Affidavit For Change Of Name After Marriage", path: "/affidavits/change-of-name-after-marriage" },
      { name: "Affidavit For Change Of Signature", path: "/affidavits/change-of-signature" },
      { name: "Affidavit For Claim Settlement In Bank", path: "/affidavits/claim-settlement-bank" },
      { name: "Affidavit For Duplicate Licence", path: "/affidavits/duplicate-licence" },
      { name: "Affidavit For Duplicate Mark sheet/Certificate", path: "/affidavits/duplicate-marksheet-certificate" },
      { name: "Affidavit For Education Loan", path: "/affidavits/education-loan" },
      { name: "Affidavit for Marriage Registration by Joint Applicants", path: "/affidavits/marriage-registration-joint-applicants" },
      { name: "Affidavit for Marriage Registration by Single Applicant", path: "/affidavits/marriage-registration-single-applicant" },
      { name: "Affidavit For One And The Same Person", path: "/affidavits/one-and-the-same-person" },
      { name: "Affidavit For Proof Of Income", path: "/affidavits/proof-of-income" },
      { name: "Affidavit In Proof Of Date Of Birth", path: "/affidavits/proof-of-date-of-birth" },
      { name: "Affidavit PF Cum Indemnity Bond", path: "/affidavits/pf-indemnity-bond" },
    ],
    "Sale Documents": [
      { name: "Agreement for sale of house", path: "/sale-documents/sale-of-house" },
      { name: "Agreement for sale of apartment in co-operative society", path: "/sale-documents/sale-of-apartment" },
      { name: "Absolute sale deed", path: "/sale-documents/absolute-sale-deed" },
      { name: "Agreement of sale", path: "/sale-documents/agreement-of-sale" },
    ],
    "E-commerce Agreements": [
      { name: "Terms of use/terms of service of e-commerce website", path: "/e-commerce-agreements/terms-of-use" },
      { name: "Privacy Policy", path: "/e-commerce-agreements/privacy-policy" },
      { name: "Cookie policy for a website", path: "/e-commerce-agreements/cookie-policy" },
      { name: "Subscription service agreement", path: "/e-commerce-agreements/subscription-service" },
      { name: "Cancellation, returns and refund policy", path: "/e-commerce-agreements/cancellation-returns-refund" },
      { name: "E-commerce website development and services agreement", path: "/e-commerce-agreements/website-development-services" },
      { name: "Terms and conditions of sale", path: "/e-commerce-agreements/terms-and-conditions-sale" },
      { name: "Internet banking services agreement", path: "/e-commerce-agreements/internet-banking-services" },
      { name: "Domain name assignment agreement", path: "/e-commerce-agreements/domain-name-assignment" },
    ],
    "Commercial Establishments": [
      { name: "Notice for Dishonour of Cheque", path: "/commercial-establishments/dishonour-of-cheque" },
      { name: "Notice of Dissolution of Partnership", path: "/commercial-establishments/dissolution-of-partnership" },
      { name: "Notice of Clearance of Dues", path: "/commercial-establishments/clearance-of-dues" },
      { name: "Notice for Faulty Product", path: "/commercial-establishments/faulty-product" },
      { name: "Notice for Non- Payment of Bill", path: "/commercial-establishments/non-payment-of-bill" },
      { name: "Notice for non-payment of salaries", path: "/commercial-establishments/non-payment-of-salaries" },
      { name: "Notice for Specific Performance Of Contract", path: "/commercial-establishments/specific-performance-contract" },
    ],
    "Intellectual Property Agreements": [
      { name: "Agreement for Sale of Technical Know-How", path: "/intellectual-property-agreements/sale-technical-know-how" },
      { name: "Deed of Assignment of Copyright", path: "/intellectual-property-agreements/assignment-copyright" },
      { name: "Agreement to sell Patent Rights", path: "/intellectual-property-agreements/sell-patent-rights" },
      { name: "Agreement for Mortgage of Patent", path: "/intellectual-property-agreements/mortgage-patent" },
      { name: "Deed of Assignment of Patents", path: "/intellectual-property-agreements/assignment-patents" },
      { name: "Agreement between Author and Publisher", path: "/intellectual-property-agreements/author-publisher" },
      { name: "Agreement between Author and New Publisher", path: "/intellectual-property-agreements/author-new-publisher" },
      { name: "Agreement for use of Trade Mark", path: "/intellectual-property-agreements/use-trade-mark" },
      { name: "Agreement between Trade Mark Owner and a Manufacturer", path: "/intellectual-property-agreements/trade-mark-owner-manufacturer" },
      { name: "Assignment of Trade Mark", path: "/intellectual-property-agreements/assignment-trade-mark" },
      { name: "Registered User Agreement", path: "/intellectual-property-agreements/registered-user" },
      { name: "Website Development Agreement", path: "/intellectual-property-agreements/website-development" },
    ],
    "Post Contractual Contracts/Matters": [
      { name: "Variation/Amendment Agreements", path: "/post-contractual/variation-amendment" },
      { name: "Termination Agreement", path: "/post-contractual/termination-agreement" },
      { name: "Side Letters", path: "/post-contractual/side-letters" },
      { name: "Interim Agreement", path: "/post-contractual/interim-agreement" },
      { name: "Change Order", path: "/post-contractual/change-order" },
      { name: "Releases/Contract Cancellation", path: "/post-contractual/releases-cancellation" },
      { name: "Post incorporation Contract Adoption", path: "/post-contractual/contract-adoption" },
    ],
    "Wills": [
      { name: "General Will", path: "/wills/general-will" },
      { name: "Islamic Will", path: "/wills/islamic-will" },
    ],
    "Power of Attorney": [
      { name: "General Power of Attorney", path: "/power-of-attorney/general" },
      { name: "Power of Attorney of Property", path: "/power-of-attorney/property" },
      { name: "Power of Attorney for NRI", path: "/power-of-attorney/nri" },
      { name: "Revocation of Power of Attorney", path: "/power-of-attorney/revocation" },
      { name: "Special Power of Attorney", path: "/power-of-attorney/special" },
      { name: "Power of Attorney for Development of Property", path: "/power-of-attorney/development" },
    ],
  };
  
  export default categoryContent;
  